drop table user_flashcard;
drop table users;
drop table flashcards;
drop table session;
drop table IDX_session_expire;

CREATE TABLE flashcards (
    id BIGSERIAL NOT NULL PRIMARY KEY,
    front VARCHAR(50) NOT NULL,
    back VARCHAR(50) NOT NULL
)
WITH (oids = false);

INSERT INTO quiz (heb, eng, difficulty) values ('ע/א', 'a/silent', 0);
INSERT INTO flashcards (front, back) values ('ב', 'b/v');
INSERT INTO flashcards (front, back) values ('ג', 'g');
INSERT INTO flashcards (front, back) values ('ד', 'd');
INSERT INTO flashcards (front, back) values ('ה', 'ha/ah');
INSERT INTO flashcards (front, back) values ('ו', 'v/o/u');
INSERT INTO flashcards (front, back) values ('ז', 'z');
INSERT INTO flashcards (front, back) values ('ח', 'kh');
INSERT INTO flashcards (front, back) values ('ט', 't');
INSERT INTO flashcards (front, back) values ('י', 'y/i');
INSERT INTO flashcards (front, back) values ('כ', 'k/kh');
INSERT INTO flashcards (front, back) values ('ך', 'kh (as the last letter of a word)');
INSERT INTO flashcards (front, back) values ('ל', 'L');
INSERT INTO flashcards (front, back) values ('מ', 'm');
INSERT INTO flashcards (front, back) values ('ם', 'm (as the last letter of a word)');
INSERT INTO flashcards (front, back) values ('נ', 'n');
INSERT INTO flashcards (front, back) values ('ן', 'n (as the last letter of a word)');
INSERT INTO flashcards (front, back) values ('ס', 's');
INSERT INTO flashcards (front, back) values ('פ', 'p/f');
INSERT INTO flashcards (front, back) values ('ף', 'f (as the last letter of a word)');
INSERT INTO flashcards (front, back) values ('צ', 'ts');
INSERT INTO flashcards (front, back) values ('ץ', 'ts (as the last letter of a word)');
INSERT INTO flashcards (front, back) values ('ק', 'k');
INSERT INTO flashcards (front, back) values ('ר', 'r');
INSERT INTO flashcards (front, back) values ('ש', 'sh/s');
INSERT INTO flashcards (front, back) values ('ת', 't');

CREATE TABLE users (
    id BIGSERIAL NOT NULL PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    email TEXT NOT NULL UNIQUE,
    hash TEXT NOT NULL,
    difficulty int default 0,
    exp int default 0
)
WITH (oids = false);

CREATE TABLE "session" (
  "sid" varchar NOT NULL COLLATE "default",
	"sess" json NOT NULL,
	"expire" timestamp(6) NOT NULL
)
WITH (OIDS=FALSE);
ALTER TABLE "session" ADD CONSTRAINT "session_pkey" PRIMARY KEY ("sid") NOT DEFERRABLE INITIALLY IMMEDIATE;
CREATE INDEX "IDX_session_expire" ON "session" ("expire");

CREATE TABLE user_flashcard (
  user_id    int REFERENCES users (id) ON UPDATE CASCADE ON DELETE CASCADE,
  flashcard_id int REFERENCES flashcards (id) ON UPDATE CASCADE,
  correctRecall int NOT NULL DEFAULT 0,
  prevInterval int default 600,
  reviewDateTime timestamptz default NOW(),

  CONSTRAINT user_flashcard_pkey PRIMARY KEY (user_id, flashcard_id)  -- explicit pk
)
WITH (oids = false);

CREATE TABLE quiz (
    id BIGSERIAL NOT NULL PRIMARY KEY,
    heb VARCHAR(50) NOT NULL,
    eng VARCHAR(50) NOT NULL,
    difficulty VARCHAR(5) NOT NULL default 0
)
WITH (oids = false);
INSERT INTO quiz (heb, eng, difficulty) values ('ע/א', 'a/silent', 0);
INSERT INTO quiz (heb, eng, difficulty) values ('ב', 'b/v', 0);
INSERT INTO quiz (heb, eng, difficulty) values ('ג', 'g', 0);
INSERT INTO quiz (heb, eng, difficulty) values ('ד', 'd', 0);
INSERT INTO quiz (heb, eng, difficulty) values ('ה', 'ha/ah', 0);
INSERT INTO quiz (heb, eng, difficulty) values ('ו', 'v/o/u', 0);
INSERT INTO quiz (heb, eng, difficulty) values ('ז', 'z', 0);
INSERT INTO quiz (heb, eng, difficulty) values ('ח', 'kh', 0);
INSERT INTO quiz (heb, eng, difficulty) values ('י', 'y/i', 0);
INSERT INTO quiz (heb, eng, difficulty) values ('כ', 'k/kh', 0);
INSERT INTO quiz (heb, eng, difficulty) values ('ך', 'kh (as the last letter of a word)', 0);
INSERT INTO quiz (heb, eng, difficulty) values ('ל', 'L', 0);
INSERT INTO quiz (heb, eng, difficulty) values ('מ', 'm', 0);
INSERT INTO quiz (heb, eng, difficulty) values ('ם', 'm (as the last letter of a word)', 0);
INSERT INTO quiz (heb, eng, difficulty) values ('נ', 'n', 0);
INSERT INTO quiz (heb, eng, difficulty) values ('ן', 'n (as the last letter of a word)', 0);
INSERT INTO quiz (heb, eng, difficulty) values ('ס', 's', 0);
INSERT INTO quiz (heb, eng, difficulty) values ('פ', 'p/f', 0);
INSERT INTO quiz (heb, eng, difficulty) values ('ף', 'f (as the last letter of a word)', 0);
INSERT INTO quiz (heb, eng, difficulty) values ('צ', 'ts', 0);
INSERT INTO quiz (heb, eng, difficulty) values ('ץ', 'ts (as the last letter of a word)', 0);
INSERT INTO quiz (heb, eng, difficulty) values ('ק', 'k', 0);
INSERT INTO quiz (heb, eng, difficulty) values ('ר', 'r', 0);
INSERT INTO quiz (heb, eng, difficulty) values ('ש', 'sh/s', 0);
INSERT INTO quiz (heb, eng, difficulty) values ('ת/ט', 't', 0);
INSERT INTO quiz (heb, eng, difficulty) values ('מנגו', 'Mango', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('בננה', 'Banana', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('מזל טוב', 'Mazal tov', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('אפריקה', 'Africa', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('פייסבוק', 'Facebook', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('אילת', 'Eilat', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('מקסיקו', 'Mexico', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('ברזיל', 'Brazil', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('איסלנד', 'Iceland', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('בר מצווה', 'Bar Mitzvah', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('בת מצווה', 'Bat Mitzvah', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('חוצפה', 'Chutzpah', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('שבת', 'Shabbat', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('או מיי גאד', 'Oh My God', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('בלגן', 'Balagan (Mess)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('פסיפיק', 'Pacific', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('אבא' ,'a-ba (dad)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('אבטיח' ,'a-va-ti-akh (watermelon)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('אביב' ,'a-viv (Spring)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('אבל' ,'a-val (but)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('אגודל' ,'a-gu-dal (thumb)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('אגס' ,'a-gas (pear)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('אדום' ,'a-dom (red)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('אוזן' ,'o-zen (ear)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('אוטובוס' ,'o-to-bus (bus)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('אוכל' ,'o-khel (food)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('אולי' ,'u-lai (maybe)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('אוניברסיטה' ,'u-ni-ver-si-ta (university)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('אופניים' ,'o-fa-na-yim (bicycle)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('אורז' ,'o-rez (rice)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('אז' ,'az (so)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('אח' ,'akh (brother)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('אחות' ,'a-khot (sister)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('איזה' ,'ei-ze (which)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('איטי' ,'i-ti (slow)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('איך' ,'eikh (how)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('אימא' ,'i-ma (mom)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('איפה' ,'ei-fo (where)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('אישה' ,'i-sha (woman/wife)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('אם' ,'im (if)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('אנגלית' ,'an-glit (English)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('אנחנו' ,'a-nakh-nu (we)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('אני' ,'a-ni (I)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('אננס' ,'a-na-nas (pineapple)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('אסור' ,'a-sur (forbidden)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('אף' ,'af (nose)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('אפרסק' ,'a-far-sek (peach)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('אפשר' ,'ef-shar (it is possible)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('ארנק' ,'ar-nak (wallet)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('אשכולית' ,'esh-ko-lit (grapefruit)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('את' ,', at (you [f])', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('אתמול' ,'et-mol (yesterday)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('בבקשה' ,'be-va-ka-sha (please)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('בגדים' ,'be-ga-dim (clothes)', 1);
INSERT INTO quiz (heb, eng ,difficulty) values ('בוקר' ,'bo-ker (morning)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('בחוץ' ,'ba-khuts (outside)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('בטטה' ,'ba-ta-ta (sweet potato)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('ביחד' ,'be-ya-khad (together)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('בינוני' ,'bei-no-ni (medium)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('ביצה' ,'bei-tsa (egg)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('בירה' ,'bi-ra (beer)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('בית' ,'ba-yit (house)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('בלי' ,'bli (without)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('בן' ,'ben (son)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('בנזין' ,'ben-zin (gasoline)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('בניין' ,'bin-yan (building)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('בננה' ,'ba-na-na (banana)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('בנק' ,'bank (bank)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('בסדר' ,'be-se-der (okay)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('בעל' ,'ba-al (husband)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('בפנים' ,'bif-nim (inside)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('בצל' ,'ba-tsal (onion)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('בקבוק' ,'bak-buk (bottle)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('בקר' ,'ba-kar (beef)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('בקרוב' ,'be-ka-rov (soon)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('בריא' ,'ba-ri (healthy)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('בשר' ,'ba-sar (meat)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('בת' ,'bat (daughter)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('גב' ,'gav (back)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('גבוה' ,'ga-vo-ha (high)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('גבינה' ,'gvi-na (cheese)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('גדול' ,'ga-dol (big)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('גובה' ,'go-va (height)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('גוף' ,'guf (body)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('גזר' ,'ge-zer (carrot)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('גלידה' ,' gli-da (ice cream)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('גם' ,'gam (also)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('גרביים' ,'gar-ba-yim (socks)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('גשם' ,'ge-shem (rain)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('דבש' ,'dvash (honey)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('דג' ,'dag (fish)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('דואר' ,'post office, do-ar (mail)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('דובדבן' ,'duv-de-van (cherry)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('דוד' ,'dod (uncle)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('דודה' ,'do-da (aunt)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('דירה' ,'di-ra (apartment)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('דלת' ,'de-let (door)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('דקה' ,'da-ka (minute)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('דרום' ,'da-rom (South)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('דרכון' ,'dar-kon (passport)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('דתי' ,'da-ti (religious)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('הבא' ,'ha-ba (next)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('הודו' ,'ho-du (turkey [food])', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('הווה' ,'ho-ve (present [tense])', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('הורים' ,'ho-rim (parents)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('היא' ,'hi (she)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('היום' ,'ha-yom (today)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('הם' ,', hem (theym)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('הן' ,', hen (theyf)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('הפסקה' ,'haf-sa-ka (break)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('הרבה' ,' har-be (alot)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('התעמלות' ,'hit-am-lut (exercise)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('זול' ,'zol (cheap)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('זית' ,'za-yit (olive)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('זמן' ,'zman (time)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('חבר' ,'kha-ver (friend)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('חג' ,'khag (holiday)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('חגורה' ,'kha-go-ra (belt)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('חדר' ,'khe-der (room)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('חדש' ,'kha-dash (new)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('חדשות' ,'kha-da-shot (news)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('חולה' ,'kho-le (sick)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('חולצה' ,'khul-tsa (shirt)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('חום' ,'khum (brown)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('חומוס' ,'khu-mus (hummus)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('חוף' ,'khof (beach)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('חופשה' ,'khuf-sha (vacation)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('חורף' ,'kho-ref (Winter)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('חזה' ,'kha-ze (chest)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('חזק' ,'kha-zak (strong)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('חלב' ,'kha-lav (milk)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('חלה' ,'kha-la (challah)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('חלון' ,'kha-lon (window)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('חלוני' ,'khi-lo-ni (secular)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('חם' ,'kham (hot)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('חמאה' ,'khem-a (butter)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('חמוצים' ,'kha-mu-tsim (pickles)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('חנות' ,'kha-nut (store)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('חסה' ,'kha-sa (lettuce)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('חצאית' ,'kha-tsa-it (skirt)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('חריף' ,'kha-rif (spicyhot)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('חשבון' ,'check, khesh-bon (bill)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('חשוב' ,'kha-shuv (important)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('חתול' ,'kha-tul (cat)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('טוב' ,'tov (good)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('טיול' ,'hike, ti-yul (trip)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('טלה' ,'ta-le (lamb)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('טלוויזיה' ,'te-le-viz-ya (tv)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('טלפון' ,'te-le-fon (telephone)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('טעים' ,'ta-im (tasty)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('יהודי' ,'ye-hu-di (Jewish)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('יוגורט' ,'yo-gurt (yogurt)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('יום' ,'yom (day)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('יין' ,'ya-yin (wine)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('ילד' ,'ye-led (boy)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('ילדה' ,'yal-da (girl)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('יפה' ,'ya-fe (beautiful)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('יציאה' ,'ye-tsi-a (exit)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('יקר' ,'ya-kar (expensive)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('ירוק' ,'ya-rok (green)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('ירח' ,'ya-re-akh (moon)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('ירקות' ,'ye-ra-kot (vegetables)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('יש' ,'yesh (there is/there are)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('ישן' ,' ya-shan (old [thing])', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('ישראל' ,'is-ra-el (Israel)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('יתוש' ,'ya-tush (mosquito)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('כאב' ,' ke-ev (painache)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('כביש' ,'route, kvish (road)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('כדור' ,'ka-dur (ball)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('כדורגל' ,'ka-du-re-gel (soccer)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('כובע' ,'ko-va (hat)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('כוכב' ,'ko-khav (star)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('כוס' ,'cup, kos (glass)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('כועס' ,'ko-es (angry)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('כחול' ,'ka-khol (blue)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('כיסא' ,'ki-se (chair)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('כיתה' ,'ki-ta (classroom)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('כל' ,'kol (all)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('כלב' ,'ke-lev (dog)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('כלום' ,'klum (nothing)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('כן' ,'ken (yes)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('כניסה' ,'kni-sa (entrance)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('כסף' ,'ke-sef (money)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('כספומט' ,'kas-po-mat (ATM)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('כף' ,'kaf (spoon)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('כרית' ,'ka-rit (pillow)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('כשר' ,'ka-sher (kosher)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('כתובת' ,'ktov-et (address)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('כתום' ,' ka-tom (orangecolor)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('לא' ,'lo (no)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('לאט' ,'le-at (slowly)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('לב' ,'lev (heart)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('לבד' ,'le-vad (alone)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('לבן' ,'la-van (white)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('להתראות' ,'le-hit-ra-ot (see you later)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('לחם' ,'le-khem (bread)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('לטאה' ,'le-ta-a (lizard)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('לילה' ,'lai-la (night)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('לימון' ,'li-mon (lemon)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('למה' ,'la-ma (why)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('למטה' ,'le-ma-ta (down)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('למעלה' ,'le-ma-la (up)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('לפני' ,'lif-nei (before)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('מאוד' ,'me-od (very)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('מאוחר' ,'me-u-khar (late)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('מאפה' ,'ma-a-fe (pastry)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('מאפייה' ,'ma-a-fi-ya (bakery)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('מבחן' ,' miv-khan (test/exam)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('מגבת' ,'ma-ge-vet (towel)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('מדינה' ,'me-di-na (country)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('מדען' ,'mad-an (scientist)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('מדפסת' ,'mad-pe-set (printer)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('מדרכה' ,'mid-ra-kha (sidewalk)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('מה' ,'ma (what)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('מהיר' ,'ma-hir (fast)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('מהנדס' ,'me-han-des (engineer)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('מהר' ,'ma-her (quickly)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('מוזיקה' ,'mu-zi-ka (music)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('מוח' ,'mo-akh (brain)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('מוכן' ,'mu-khan (ready)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('מונית' ,'mo-nit (taxi)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('מורה' ,'mo-re, mo-ra (teacher)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('מזג אוויר','me-zeg a-vir (weather)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('מזגן' ,' maz-gan (airconditioner)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('מזלג' ,'maz-leg (fork)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('מזרח' ,'miz-rakh (East)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('מחברת' ,'makh-be-ret (notebook)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('מחר' ,'ma-khar (tomorrow)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('מחשב' ,'makh-shev (computer)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('מטבח' ,'mit-bakh (kitchen)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('מטוגן' ,'me-tu-gan (fried)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('מטוס' ,'ma-tos (airplane)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('מטר' ,'me-ter (meter)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('מי' ,'mi (who)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('מיטה' ,'mi-ta (bed)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('מילון' ,'mi-lon (dictionary)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('מים' ,'ma-yim (water)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('מיץ' ,'mits (juice)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('מיקרוגל' ,'mik-ro-gal (microwave)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('מישהו' ,'mi-she-hu (someone)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('מכוער' ,'me-kho-ar (ugly)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('מכנסים' ,'mikh-na-sa-yim (pants)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('מלא' ,'ma-le (full)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('מלהיב' ,'mal-hiv (exciting)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('מלון' ,'ma-lon (hotel)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('מלח' ,'me-lakh (salt)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('מלפפון' ,'me-la-fe-fon (cucumber)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('ממשלה' ,'mem-sha-la (government)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('מנגו' ,'man-go (mango)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('מנהל' ,'me-na-hel (manager)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('מנהרה' ,'min-ha-ra (tunnel)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('מסעדה' ,'mis-a-da (restaurant)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('מספר' ,'mis-par (number)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('מסריח' ,'mas-ri-akh (smelly)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('מעניין' ,'me-an-yen (interesting)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('מערב' ,'ma-a-rav (West)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('מפית' ,'map-it (napkin)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('מפתח' ,'maf-te-akh (key)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('מצוין' ,'me-tsu-yan (excellent)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('מצחיק' ,'mats-khik (funny)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('מקום' ,'ma-kom (place)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('מקרר' ,'me-ka-rer (refrigerator)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('משהו' ,'ma-she-hu (something)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('משחק' ,'mis-khak (game)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('משטרה' ,'mish-ta-ra (police)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('משפחה' ,'mish-pa-kha (family)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('משקל' ,'mish-kal (weight)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('משרד' ,'mis-rad (office)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('מתוק' ,'ma-tok (sweet)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('מתי' ,'ma-tai (when)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('נבון' ,'na-von (intelligent)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('נהג' ,'na-hag (driver)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('נהר' ,'na-har (river)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('נמוך' ,'na-mukh (low)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('נמלה' ,'ne-ma-la (ant)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('נעליים' ,'na-a-la-yim (shoes)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('נקטרינה' ,'nek-ta-ri-na (nectarine)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('נקי' ,'na-ki (clean)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('נשוי' ,'na-su-i (married)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('סבא' ,'sa-ba (grandfather)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('סבון' ,'sa-bon (soap)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('סבתא' ,'sav-ta (grandmother)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('סגול' ,'sa-gol (purple)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('סדין' ,'sa-din (sheet)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('סוכר' ,'su-kar (sugar)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('סוף' ,'sof (end)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('סופרמרקט' ,'su-per-mar-ket (supermarket)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('סטודנט' ,'stu-dent (student)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('סיפור' ,'si-pur (story)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('סכין' ,'sa-kin (knife)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('סלט' ,'sa-lat (salad)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('סליחה' ,'sli-kha (excuse me/sorry)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('סלק' ,' se-lek (beetroot)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('סנדלים' ,'san-da-lim (sandals)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('ספה' ,'sa-pa (sofa)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('ספורט' ,'sport (sport)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('ספר' ,'se-fer (book)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('ספרייה' ,'sif-ri-ya (library)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('סרט' ,'se-ret (movie)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('סתיו' ,'stav (Fall)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('עבר' ,'a-var (past)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('עברית' ,'iv-rit (Hebrew)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('עגבניה' ,'ag-va-ni-ya (tomato)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('עובש' ,'o-vesh (mold)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('עוגה' ,'u-ga (cake)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('עולם' ,'o-lam (world)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('עוף' ,'of (chicken)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('עט' ,'et (pen)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('עייף' ,'a-yef (tired)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('עין' ,'a-yin (eye)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('עיר' ,'ir (city)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('עיתון' ,'i-ton (newspaper)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('עכביש' ,'a-ka-vish (spider)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('עכשיו' ,'akh-shav (now)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('על' ,'al (about/on)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('ענבים' ,'a-na-vim (grapes)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('עני' ,'a-ni (poor)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('ענן' ,'a-nan (cloud)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('עפרון' ,'i-pa-ron (pencil)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('עצור' ,'a-tsor (stop)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('עצלן' ,'ats-lan (lazy)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('עצם' ,'e-tsem (bone)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('ערב' ,'e-rev (evening)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('ערבית' ,'a-ra-vit (Arabic)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('ערוץ' ,' a-ruts (channeltv)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('עשיר' ,'a-shir (rich)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('עתיד' ,'a-tid (future)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('פה' ,'pe (mouth)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('פה' ,'po (here)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('פטרוזיליה' ,'pet-ro-zil-ya (parsley)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('פטריות' ,'pit-ri-yot (mushrooms)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('פיקח' ,'pi-ke-akh (smart)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('פיתה' ,'pi-ta (pita)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('פלאפל' ,'fa-la-fel (falafel)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('פלפל' ,'pil-pel (pepper)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('פנים' ,'pa-nim (face)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('פסטה' ,'pas-ta (pasta)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('פסנתר' ,'psan-ter (piano)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('פעם' ,'pa-am (once)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('פעמים' ,'pa-a-ma-yim (twice)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('פקולטה' ,'fa-kul-ta (faculty)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('פרי' ,'pri (fruit)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('פרק' ,'pe-rek (chapter)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('פשוט' ,'pa-shut (simple)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('פתוח' ,'pa-tu-akh (open)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('צבע' ,'tse-va (color)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('צהוב' ,'tsa-hov (yellow)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('צהריים' ,'tso-ho-ra-yim (noon)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('צלחת' ,'tsa-la-khat (plate)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('צפון' ,'tsa-fon (North)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('קבוצה' ,'kvu-tsa (team)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('קטן' ,'ka-tan (small)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('קינואה' ,'ki-no-a (quinoa)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('קיץ' ,'ka-yits (Summer)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('קיר' ,'kir (wall)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('קל' ,'kal (easy)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('קניון' ,'kan-yon (mall)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('קערה' ,'ke-a-ra (bowl)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('קפה' ,'ka-fe (coffee)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('קצת' ,'k-tsat (a little)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('קר' ,'kar (cold)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('קשה' ,'ka-she (difficult)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('ראש' ,'rosh (head)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('ראשון' ,'ri-shon (first)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('רב' ,'rav (rabbi)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('רבע' ,'something, re-va (quarterof)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('רגל' ,'re-gel (leg)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('רגע' ,'re-ga (moment)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('רוטב' ,'ro-tev (sauce)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('רועש' ,'ro-esh (noisy)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('רופא' ,'physician, ro-fe (doctor)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('רזה' ,'ra-ze (thin)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('רחוב' ,'re-khov (street)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('רטוב' ,'ra-tov (wet)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('רימון' ,'ri-mon (pomegranate)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('רך' ,'rakh (soft)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('רכבת' ,'ra-ke-vet (train)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('רע' ,'ra (bad)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('רעב' ,'ra-ev (hungry)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('רעיון' ,'ra-a-yon (idea)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('רצפה' ,'rits-pa (floor)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('רק' ,'rak (only)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('שאלה' ,'she-e-la (question)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('שבוע' ,'sha-vu-a (week)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('שבת' ,'sha-bat (Saturday)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('שוב' ,'shuv (again)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('שווארמה' ,'sha-war-ma (shawarma)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('שולחן' ,'shul-khan (table)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('שום' ,'shum (garlic)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('שוקולד' ,'sho-ko-lad (chocolate)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('שזיף' ,'she-zif (plum)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('שחור' ,'sha-khor (black)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('שחייה' ,'skhi-ya (swimming)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('שטיח' ,'sha-ti-akh (rug)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('שיעור' ,'shi-ur (lesson)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('שירות' ,'shei-rut (shuttle taxi)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('שכונה' ,'shkhu-na (neighborhood)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('של' ,'shel (of)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('שלום' ,'sha-lom (hello)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('שליש' ,'something, shlish (thirdof)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('שלם' ,'sha-lem (whole)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('שם' ,'sham (there)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('שם' ,'shem (name)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('שמאלה' ,'smo-la (left [direction])', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('שמיים' ,'sha-ma-yim (sky)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('שמן' ,'she-men (oil)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('שמן' ,'sha-men (fat)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('שמש' ,'she-mesh (sun)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('שניה' ,'shni-ya (second [time])', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('שניצל' ,'shni-tsel (schnitzel)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('שעה' ,'sha-a (hour)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('שעון' ,'sha-on (clock)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('שער' ,'se-ar (hair)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('שפה' ,'sa-fa (language)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('שקד' ,'sha-ked (almond)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('שקל' ,'she-kel (shekel)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('שקשוקה' ,'shak-shu-ka (shakshuka)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('שרותים' ,'she-ru-tim (toilet/bathroom)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('תה' ,'te (tea)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('תודה' ,'to-da (thank you)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('תות' ,'tut (strawberry)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('תינוק' ,'ti-nok (baby)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('תיק' ,'tik (bag)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('תמונה' ,'tmu-na (picture)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('תמר' ,'ta-mar (date [food])', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('תנור' ,'ta-nur (oven)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('תפוז' ,'ta-puz (orange [food])', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('תפוח' ,'ta-pu-akh (apple)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('תקרה' ,'tik-ra (ceiling)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('תרד' ,'te-red (spinach)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('תשובה' ,'tshu-va (answer)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('אתה' ,'a-ta (you[m])', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('הוא' ,'hu (he)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('זה' ,'ze (this)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('זקן' ,'za-ken (oldperson)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('חברה' ,'khev-ra (company)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('חודש' ,'kho-desh (month)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('חצי' ,'khe-tsi (half of something)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('ים' ,'yam (sea)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('כדורסל' ,'ka-dur-sal (basketball)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('כרוב' ,'kruv (cabbage)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('מדבר' ,'mid-bar (desert)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('מוזיאון' ,'mu-zei-on (museum)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('מוקדם' ,'muk-dam (early)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('מכונית' ,'me-kho-nit (car)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('מצלמה' ,'mats-le-ma (camera)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('מרק' ,'ma-rak (soup)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('משעמם' ,'me-sha-a-mem (boring)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('נייר' ,'ni-yar (paper)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('נכון' ,'na-khon (correct)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('סגור' ,'sa-gur (closed)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('ציפור' ,'tsi-por (bird)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('שיניים' ,'shi-na-yim (teeth)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('שנה' ,'sha-na (year)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('שקט' ,'she-ket (quiet)', 1);
INSERT INTO quiz (heb, eng, difficulty) values ('תחביב' ,'takh-biv (hobby)', 1);